// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import FloatingWhatsApp from "@/components/ui/FloatingWhatsApp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  // metadataBase: new URL("https://bintangcreative.com"),
  title: {
    default: "Segala Vendor",
    template:
      "%s | Bintang Creative Nusantara - Event Organizer & Vendor Terpercaya",
  },
  description:
    "Event organizer #1 di Jakarta, Bandung, Surabaya. Vendor sewa alat sound system, lighting, panggung terlengkap. Agency talent MC, host, model professional. Harga terjangkau, garansi 100%. Konsultasi gratis!",

  keywords: [
    // Primary Keywords (High Priority)
    "event organizer jakarta",
    "vendor sewa alat jakarta",
    "agency talent jakarta",
    "event organizer bandung",
    "vendor sewa alat bandung",
    "agency talent bandung",
    "event organizer surabaya",
    "vendor sewa alat surabaya",
    "agency talent surabaya",

    // Secondary Keywords (Medium Priority)
    "sewa sound system jakarta",
    "sewa lighting jakarta",
    "sewa panggung jakarta",
    "mc professional jakarta",
    "host event jakarta",
    "model talent jakarta",
    "wedding organizer jakarta",
    "corporate event jakarta",
    "event organizer murah jakarta",
    "vendor event jakarta",
    "agency mc jakarta",
    "sewa alat event jakarta",

    // Long-tail Keywords (High Converting)
    "event organizer jakarta selatan",
    "event organizer jakarta barat",
    "event organizer jakarta timur",
    "event organizer jakarta utara",
    "event organizer jakarta pusat",
    "vendor sewa alat bogor",
    "vendor sewa alat depok",
    "vendor sewa alat tangerang",
    "vendor sewa alat bekasi",
    "agency talent bandung barat",
    "agency talent cimahi",
    "event organizer yogyakarta",
    "event organizer solo",
    "event organizer malang",
    "event organizer denpasar",
    "event organizer ubud",

    // Service-based Keywords
    "sewa sound system professional",
    "sewa lighting led",
    "sewa panggung outdoor",
    "sewa panggung indoor",
    "mc wedding professional",
    "mc corporate event",
    "host acara professional",
    "model photoshoot jakarta",
    "talent show jakarta",
    "crew event professional",
    "security event jakarta",
    "catering event jakarta",
    "dekorasi event jakarta",
    "dokumentasi event jakarta",
    "live streaming event",

    // Event Type Keywords
    "wedding organizer murah",
    "corporate event organizer",
    "birthday party organizer",
    "seminar organizer jakarta",
    "conference organizer jakarta",
    "exhibition organizer jakarta",
    "product launch organizer",
    "grand opening organizer",
    "company gathering organizer",
    "school event organizer",
    "university event organizer",
    "government event organizer",
    "concert organizer jakarta",
    "festival organizer jakarta",
    "sports event organizer",
    "charity event organizer",
    "religious event organizer",
    "fashion show organizer",
    "beauty contest organizer",
    "singing competition organizer",
    "dance competition organizer",
    "art exhibition organizer",
    "food festival organizer",
    "music festival organizer",
    "job fair organizer",
    "education fair organizer",
    "property expo organizer",
    "automotive expo organizer",
    "technology expo organizer",
    "health expo organizer",
    "business conference organizer",
    "webinar organizer jakarta",
    "virtual event organizer",
    "hybrid event organizer",
    "outdoor event organizer",
    "indoor event organizer",
    "hotel event organizer",
    "ballroom event organizer",
    "mall event organizer",
    "restaurant event organizer",

    // Equipment Rental Keywords
    "rental sound system jakarta",
    "rental lighting jakarta",
    "rental panggung jakarta",
    "rental backdrop jakarta",
    "rental kursi jakarta",
    "rental meja jakarta",
    "rental tenda jakarta",
    "rental genset jakarta",
    "rental proyektor jakarta",
    "rental led screen jakarta",
    "rental kamera jakarta",
    "rental microphone jakarta",
    "rental speaker jakarta",
    "rental mixer jakarta",
    "rental drumset jakarta",
    "rental keyboard jakarta",
    "rental gitar jakarta",
    "rental kostum jakarta",
    "rental rias jakarta",
    "rental mobil jakarta",
    "rental bus jakarta",
    "rental toilet portable",
    "rental air conditioning",
    "rental fan jakarta",
    "rental carpet jakarta",
    "rental red carpet jakarta",
    "rental gazebo jakarta",
    "rental canopy jakarta",
    "rental barricade jakarta",
    "rental security jakarta",

    // Talent Agency Keywords
    "talent agency jakarta",
    "modeling agency jakarta",
    "mc agency jakarta",
    "host agency jakarta",
    "singer agency jakarta",
    "dancer agency jakarta",
    "musician agency jakarta",
    "entertainer agency jakarta",
    "performer agency jakarta",
    "artist agency jakarta",
    "celebrity agency jakarta",
    "influencer agency jakarta",
    "presenter agency jakarta",
    "narrator agency jakarta",
    "voice over agency jakarta",
    "translator agency jakarta",
    "interpreter agency jakarta",
    "photographer agency jakarta",
    "videographer agency jakarta",
    "makeup artist agency jakarta",
    "hair stylist agency jakarta",
    "costume designer agency jakarta",
    "choreographer agency jakarta",
    "director agency jakarta",
    "producer agency jakarta",
    "editor agency jakarta",
    "graphic designer agency jakarta",
    "web designer agency jakarta",
    "social media specialist agency",
    "content creator agency jakarta",
    "copywriter agency jakarta",
    "marketing specialist agency jakarta",
    "event coordinator agency jakarta",
    "project manager agency jakarta",
    "technical crew agency jakarta",
    "lighting technician agency jakarta",
    "sound technician agency jakarta",
    "camera operator agency jakarta",
    "stage manager agency jakarta",
    "production assistant agency jakarta",
    "logistics coordinator agency jakarta",
    "transportation coordinator agency jakarta",
    "catering coordinator agency jakarta",
    "decoration coordinator agency jakarta",
    "protocol officer agency jakarta",
    "liaison officer agency jakarta",
    "public relations officer agency jakarta",
    "media relations officer agency jakarta",
    "customer service officer agency jakarta",
    "registration officer agency jakarta",
    "information desk officer agency jakarta",
    "security officer agency jakarta",
    "parking officer agency jakarta",
    "cleaning service agency jakarta",
    "maintenance service agency jakarta",
    "medical service agency jakarta",
    "first aid service agency jakarta",

    // Local SEO Keywords
    "event organizer jakarta selatan terdekat",
    "event organizer jakarta barat terdekat",
    "event organizer jakarta timur terdekat",
    "event organizer jakarta utara terdekat",
    "event organizer jakarta pusat terdekat",
    "vendor sewa alat terdekat",
    "agency talent terdekat",
    "event organizer 24 jam jakarta",
    "event organizer emergency jakarta",
    "event organizer same day jakarta",
    "event organizer weekend jakarta",
    "event organizer holiday jakarta",
    "event organizer express jakarta",
    "event organizer urgent jakarta",
    "event organizer last minute jakarta",

    // Budget-based Keywords
    "event organizer murah jakarta",
    "event organizer terjangkau jakarta",
    "event organizer budget jakarta",
    "event organizer hemat jakarta",
    "event organizer ekonomis jakarta",
    "event organizer promo jakarta",
    "event organizer diskon jakarta",
    "event organizer paket jakarta",
    "event organizer all in one jakarta",
    "event organizer lengkap jakarta",
    "event organizer professional jakarta",
    "event organizer terpercaya jakarta",
    "event organizer berpengalaman jakarta",
    "event organizer berkualitas jakarta",
    "event organizer terbaik jakarta",
    "event organizer nomor 1 jakarta",
    "event organizer recommended jakarta",
    "event organizer favorit jakarta",
    "event organizer populer jakarta",
    "event organizer terkenal jakarta",

    // Competitor Keywords
    "event organizer jakarta vs bandung",
    "vendor sewa alat jakarta vs surabaya",
    "agency talent jakarta vs bali",
    "event organizer indonesia terbaik",
    "vendor sewa alat indonesia terlengkap",
    "agency talent indonesia terpercaya",
    "event organizer nasional",
    "vendor sewa alat nasional",
    "agency talent nasional",
    "event organizer internasional",
    "vendor sewa alat internasional",
    "agency talent internasional",

    // Question-based Keywords (Voice Search)
    "event organizer jakarta yang bagus",
    "vendor sewa alat jakarta yang murah",
    "agency talent jakarta yang professional",
    "dimana event organizer terbaik jakarta",
    "berapa harga event organizer jakarta",
    "kapan booking event organizer jakarta",
    "bagaimana cara booking event organizer",
    "siapa event organizer terpercaya jakarta",
    "mengapa pilih event organizer jakarta",
    "apa saja layanan event organizer",
    "event organizer jakarta rekomendasi",
    "event organizer jakarta review",
    "event organizer jakarta testimoni",
    "event organizer jakarta portofolio",
    "event organizer jakarta pengalaman",
    "event organizer jakarta garansi",
    "event organizer jakarta asuransi",
    "event organizer jakarta sertifikat",
    "event organizer jakarta legal",
    "event organizer jakarta resmi",
    "event organizer jakarta ijin",
    "event organizer jakarta license",
    "event organizer jakarta kredible",
    "event organizer jakarta bonafide",
    "event organizer jakarta established",
    "event organizer jakarta since",
    "event organizer jakarta history",
    "event organizer jakarta track record",
    "event organizer jakarta client",
    "event organizer jakarta customer",
    "event organizer jakarta partner",
    "event organizer jakarta network",
    "event organizer jakarta collaboration",
    "event organizer jakarta joint venture",
    "event organizer jakarta franchise",
    "event organizer jakarta branch",
    "event organizer jakarta office",
    "event organizer jakarta contact",
    "event organizer jakarta address",
    "event organizer jakarta location",
    "event organizer jakarta map",
    "event organizer jakarta direction",
    "event organizer jakarta transportation",
    "event organizer jakarta access",
    "event organizer jakarta facility",
    "event organizer jakarta warehouse",
    "event organizer jakarta storage",
    "event organizer jakarta inventory",
    "event organizer jakarta stock",
    "event organizer jakarta equipment",
    "event organizer jakarta tools",
    "event organizer jakarta technology",
    "event organizer jakarta innovation",
    "event organizer jakarta update",
    "event organizer jakarta latest",
    "event organizer jakarta modern",
    "event organizer jakarta advanced",
    "event organizer jakarta sophisticated",
    "event organizer jakarta cutting edge",
    "event organizer jakarta state of the art",
    "event organizer jakarta world class",
    "event organizer jakarta international standard",
    "event organizer jakarta ISO certified",
    "event organizer jakarta quality assurance",
    "event organizer jakarta quality control",
    "event organizer jakarta best practice",
    "event organizer jakarta standard operating procedure",
    "event organizer jakarta management system",
    "event organizer jakarta workflow",
    "event organizer jakarta process",
    "event organizer jakarta methodology",
    "event organizer jakarta approach",
    "event organizer jakarta strategy",
    "event organizer jakarta solution",
    "event organizer jakarta concept",
    "event organizer jakarta idea",
    "event organizer jakarta creativity",
    "event organizer jakarta innovation",
    "event organizer jakarta uniqueness",
    "event organizer jakarta differentiation",
    "event organizer jakarta competitive advantage",
    "event organizer jakarta value proposition",
    "event organizer jakarta benefit",
    "event organizer jakarta advantage",
    "event organizer jakarta strength",
    "event organizer jakarta expertise",
    "event organizer jakarta specialization",
    "event organizer jakarta focus",
    "event organizer jakarta niche",
    "event organizer jakarta segment",
    "event organizer jakarta market",
    "event organizer jakarta industry",
    "event organizer jakarta sector",
    "event organizer jakarta vertical",
    "event organizer jakarta horizontal",
    "event organizer jakarta integration",
    "event organizer jakarta synergy",
    "event organizer jakarta collaboration",
    "event organizer jakarta partnership",
    "event organizer jakarta alliance",
    "event organizer jakarta ecosystem",
    "event organizer jakarta community",
    "event organizer jakarta network",
    "event organizer jakarta connection",
    "event organizer jakarta relationship",
    "event organizer jakarta engagement",
    "event organizer jakarta interaction",
    "event organizer jakarta communication",
    "event organizer jakarta dialogue",
    "event organizer jakarta consultation",
    "event organizer jakarta advisory",
    "event organizer jakarta guidance",
    "event organizer jakarta support",
    "event organizer jakarta assistance",
    "event organizer jakarta help",
    "event organizer jakarta service",
    "event organizer jakarta care",
    "event organizer jakarta attention",
    "event organizer jakarta dedication",
    "event organizer jakarta commitment",
    "event organizer jakarta responsibility",
    "event organizer jakarta accountability",
    "event organizer jakarta reliability",
    "event organizer jakarta dependability",
    "event organizer jakarta consistency",
    "event organizer jakarta stability",
    "event organizer jakarta sustainability",
    "event organizer jakarta continuity",
    "event organizer jakarta longevity",
    "event organizer jakarta endurance",
    "event organizer jakarta persistence",
    "event organizer jakarta resilience",
    "event organizer jakarta adaptability",
    "event organizer jakarta flexibility",
    "event organizer jakarta agility",
    "event organizer jakarta responsiveness",
    "event organizer jakarta speed",
    "event organizer jakarta efficiency",
    "event organizer jakarta effectiveness",
    "event organizer jakarta productivity",
    "event organizer jakarta performance",
    "event organizer jakarta result",
    "event organizer jakarta outcome",
    "event organizer jakarta achievement",
    "event organizer jakarta success",
    "event organizer jakarta excellence",
    "event organizer jakarta superiority",
    "event organizer jakarta leadership",
    "event organizer jakarta pioneering",
    "event organizer jakarta trendsetter",
    "event organizer jakarta innovator",
    "event organizer jakarta game changer",
    "event organizer jakarta market leader",
    "event organizer jakarta industry leader",
    "event organizer jakarta thought leader",
    "event organizer jakarta opinion leader",
    "event organizer jakarta influencer",
    "event organizer jakarta authority",
    "event organizer jakarta expert",
    "event organizer jakarta specialist",
    "event organizer jakarta professional",
    "event organizer jakarta consultant",
    "event organizer jakarta advisor",
    "event organizer jakarta mentor",
    "event organizer jakarta coach",
    "event organizer jakarta trainer",
    "event organizer jakarta instructor",
    "event organizer jakarta educator",
    "event organizer jakarta teacher",
    "event organizer jakarta facilitator",
    "event organizer jakarta moderator",
    "event organizer jakarta mediator",
    "event organizer jakarta negotiator",
    "event organizer jakarta arbitrator",
    "event organizer jakarta coordinator",
    "event organizer jakarta manager",
    "event organizer jakarta director",
    "event organizer jakarta executive",
    "event organizer jakarta leader",
    "event organizer jakarta chief",
    "event organizer jakarta head",
    "event organizer jakarta president",
    "event organizer jakarta vice president",
    "event organizer jakarta chairman",
    "event organizer jakarta founder",
    "event organizer jakarta owner",
    "event organizer jakarta partner",
    "event organizer jakarta stakeholder",
    "event organizer jakarta shareholder",
    "event organizer jakarta investor",
    "event organizer jakarta sponsor",
    "event organizer jakarta supporter",
    "event organizer jakarta patron",
    "event organizer jakarta benefactor",
    "event organizer jakarta contributor",
    "event organizer jakarta donor",
    "event organizer jakarta volunteer",
    "event organizer jakarta advocate",
    "event organizer jakarta ambassador",
    "event organizer jakarta representative",
    "event organizer jakarta delegate",
    "event organizer jakarta spokesperson",
    "event organizer jakarta communicator",
    "event organizer jakarta messenger",
    "event organizer jakarta herald",
    "event organizer jakarta announcer",
    "event organizer jakarta broadcaster",
    "event organizer jakarta publisher",
    "event organizer jakarta editor",
    "event organizer jakarta writer",
    "event organizer jakarta author",
    "event organizer jakarta creator",
    "event organizer jakarta producer",
    "event organizer jakarta developer",
    "event organizer jakarta designer",
    "event organizer jakarta architect",
    "event organizer jakarta builder",
    "event organizer jakarta constructor",
    "event organizer jakarta installer",
    "event organizer jakarta implementer",
    "event organizer jakarta executor",
    "event organizer jakarta operator",
    "event organizer jakarta user",
    "event organizer jakarta consumer",
    "event organizer jakarta customer",
    "event organizer jakarta client",
    "event organizer jakarta patron",
    "event organizer jakarta subscriber",
    "event organizer jakarta member",
    "event organizer jakarta participant",
    "event organizer jakarta attendee",
    "event organizer jakarta guest",
    "event organizer jakarta visitor",
    "event organizer jakarta observer",
    "event organizer jakarta watcher",
    "event organizer jakarta viewer",
    "event organizer jakarta listener",
    "event organizer jakarta reader",
    "event organizer jakarta learner",
    "event organizer jakarta student",
    "event organizer jakarta trainee",
    "event organizer jakarta apprentice",
    "event organizer jakarta novice",
    "event organizer jakarta beginner",
    "event organizer jakarta amateur",
    "event organizer jakarta hobbyist",
    "event organizer jakarta enthusiast",
    "event organizer jakarta aficionado",
    "event organizer jakarta connoisseur",
    "event organizer jakarta expert",
    "event organizer jakarta master",
    "event organizer jakarta professional",
    "event organizer jakarta veteran",
    "event organizer jakarta senior",
    "event organizer jakarta experienced",
    "event organizer jakarta seasoned",
    "event organizer jakarta skilled",
    "event organizer jakarta talented",
    "event organizer jakarta gifted",
    "event organizer jakarta capable",
    "event organizer jakarta competent",
    "event organizer jakarta qualified",
    "event organizer jakarta certified",
    "event organizer jakarta licensed",
    "event organizer jakarta accredited",
    "event organizer jakarta authorized",
    "event organizer jakarta approved",
    "event organizer jakarta endorsed",
    "event organizer jakarta recommended",
    "event organizer jakarta preferred",
    "event organizer jakarta selected",
    "event organizer jakarta chosen",
    "event organizer jakarta nominated",
    "event organizer jakarta awarded",
    "event organizer jakarta recognized",
    "event organizer jakarta acknowledged",
    "event organizer jakarta appreciated",
    "event organizer jakarta valued",
    "event organizer jakarta respected",
    "event organizer jakarta admired",
    "event organizer jakarta praised",
    "event organizer jakarta commended",
    "event organizer jakarta celebrated",
    "event organizer jakarta honored",
    "event organizer jakarta distinguished",
    "event organizer jakarta prominent",
    "event organizer jakarta notable",
    "event organizer jakarta remarkable",
    "event organizer jakarta outstanding",
    "event organizer jakarta exceptional",
    "event organizer jakarta extraordinary",
    "event organizer jakarta incredible",
    "event organizer jakarta amazing",
    "event organizer jakarta fantastic",
    "event organizer jakarta wonderful",
    "event organizer jakarta excellent",
    "event organizer jakarta superb",
    "event organizer jakarta superior",
    "event organizer jakarta premium",
    "event organizer jakarta deluxe",
    "event organizer jakarta luxury",
    "event organizer jakarta exclusive",
    "event organizer jakarta elite",
    "event organizer jakarta VIP",
    "event organizer jakarta VVIP",
    "event organizer jakarta first class",
    "event organizer jakarta world class",
    "event organizer jakarta international class",
    "event organizer jakarta global class",
    "event organizer jakarta universal class",
    "event organizer jakarta standard class",
    "event organizer jakarta economy class",
    "event organizer jakarta budget class",
    "event organizer jakarta affordable class",
    "event organizer jakarta cheap class",
    "event organizer jakarta low cost",
    "event organizer jakarta high quality",
    "event organizer jakarta best quality",
    "event organizer jakarta top quality",
    "event organizer jakarta premium quality",
    "event organizer jakarta superior quality",
    "event organizer jakarta excellent quality",
    "event organizer jakarta outstanding quality",
    "event organizer jakarta exceptional quality",
    "event organizer jakarta world class quality",
    "event organizer jakarta international quality",
    "event organizer jakarta global quality",
    "event organizer jakarta universal quality",
    "event organizer jakarta standard quality",
    "event organizer jakarta guaranteed quality",
    "event organizer jakarta assured quality",
    "event organizer jakarta certified quality",
    "event organizer jakarta tested quality",
    "event organizer jakarta proven quality",
    "event organizer jakarta reliable quality",
    "event organizer jakarta consistent quality",
    "event organizer jakarta stable quality",
    "event organizer jakarta sustainable quality",
    "event organizer jakarta continuous quality",
    "event organizer jakarta long lasting quality",
    "event organizer jakarta durable quality",
    "event organizer jakarta enduring quality",
    "event organizer jakarta persistent quality",
    "event organizer jakarta resilient quality",
    "event organizer jakarta adaptable quality",
    "event organizer jakarta flexible quality",
    "event organizer jakarta agile quality",
    "event organizer jakarta responsive quality",
    "event organizer jakarta fast quality",
    "event organizer jakarta quick quality",
    "event organizer jakarta speedy quality",
    "event organizer jakarta rapid quality",
    "event organizer jakarta swift quality",
    "event organizer jakarta immediate quality",
    "event organizer jakarta instant quality",
    "event organizer jakarta real time quality",
    "event organizer jakarta live quality",
    "event organizer jakarta current quality",
    "event organizer jakarta updated quality",
    "event organizer jakarta latest quality",
    "event organizer jakarta newest quality",
    "event organizer jakarta modern quality",
    "event organizer jakarta contemporary quality",
    "event organizer jakarta advanced quality",
    "event organizer jakarta sophisticated quality",
    "event organizer jakarta cutting edge quality",
    "event organizer jakarta state of the art quality",
    "event organizer jakarta innovative quality",
    "event organizer jakarta creative quality",
    "event organizer jakarta unique quality",
    "event organizer jakarta original quality",
    "event organizer jakarta authentic quality",
    "event organizer jakarta genuine quality",
    "event organizer jakarta real quality",
    "event organizer jakarta true quality",
    "event organizer jakarta honest quality",
    "event organizer jakarta transparent quality",
    "event organizer jakarta open quality",
    "event organizer jakarta clear quality",
    "event organizer jakarta obvious quality",
    "event organizer jakarta evident quality",
    "event organizer jakarta apparent quality",
    "event organizer jakarta visible quality",
    "event organizer jakarta noticeable quality",
    "event organizer jakarta recognizable quality",
    "event organizer jakarta identifiable quality",
    "event organizer jakarta distinguishable quality",
    "event organizer jakarta memorable quality",
    "event organizer jakarta unforgettable quality",
    "event organizer jakarta remarkable quality",
    "event organizer jakarta impressive quality",
    "event organizer jakarta striking quality",
    "event organizer jakarta stunning quality",
    "event organizer jakarta breathtaking quality",
    "event organizer jakarta spectacular quality",
    "event organizer jakarta magnificent quality",
    "event organizer jakarta splendid quality",
    "event organizer jakarta gorgeous quality",
    "event organizer jakarta beautiful quality",
    "event organizer jakarta attractive quality",
    "event organizer jakarta appealing quality",
    "event organizer jakarta charming quality",
    "event organizer jakarta delightful quality",
    "event organizer jakarta pleasant quality",
    "event organizer jakarta enjoyable quality",
    "event organizer jakarta satisfying quality",
    "event organizer jakarta fulfilling quality",
    "event organizer jakarta rewarding quality",
    "event organizer jakarta valuable quality",
    "event organizer jakarta worthwhile quality",
    "event organizer jakarta beneficial quality",
    "event organizer jakarta advantageous quality",
    "event organizer jakarta profitable quality",
    "event organizer jakarta productive quality",
    "event organizer jakarta effective quality",
    "event organizer jakarta efficient quality",
    "event organizer jakarta successful quality",
    "event organizer jakarta winning quality",
    "event organizer jakarta champion quality",
    "event organizer jakarta leader quality",
    "event organizer jakarta pioneer quality",
    "event organizer jakarta trendsetter quality",
    "event organizer jakarta innovator quality",
    "event organizer jakarta game changer quality",
    "event organizer jakarta market leader quality",
    "event organizer jakarta industry leader quality",
    "event organizer jakarta thought leader quality",
    "event organizer jakarta opinion leader quality",
    "event organizer jakarta influencer quality",
    "event organizer jakarta authority quality",
    "event organizer jakarta expert quality",
    "event organizer jakarta specialist quality",
    "event organizer jakarta professional quality",
    "event organizer jakarta consultant quality",
    "event organizer jakarta advisor quality",
    "event organizer jakarta mentor quality",
    "event organizer jakarta coach quality",
    "event organizer jakarta trainer quality",
    "event organizer jakarta instructor quality",
    "event organizer jakarta educator quality",
    "event organizer jakarta teacher quality",
    "event organizer jakarta facilitator quality",
    "event organizer jakarta moderator quality",
  ],

  // Enhanced Open Graph for Social Media
  openGraph: {
    title:
      "Event Organizer Jakarta | Vendor Sewa Alat | Agency Talent Professional",
    description:
      "Event organizer #1 di Jakarta, Bandung, Surabaya. Vendor sewa alat sound system, lighting, panggung terlengkap. Agency talent MC, host, model professional. Harga terjangkau, garansi 100%.",
    url: "https://bintangcreative.com",
    siteName: "Bintang Creative Nusantara",
    images: [
      {
        url: "https://bintangcreative.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Event Organizer Jakarta - Bintang Creative Nusantara",
      },
    ],
    locale: "id_ID",
    type: "website",
  },

  // Twitter Card
  twitter: {
    card: "summary_large_image",
    title:
      "Event Organizer Jakarta | Vendor Sewa Alat | Agency Talent Professional",
    description:
      "Event organizer #1 di Jakarta, Bandung, Surabaya. Vendor sewa alat terlengkap. Agency talent professional. Harga terjangkau, garansi 100%.",
    images: ["https://bintangcreative.com/twitter-image.jpg"],
    creator: "@bintangcreative",
    site: "@bintangcreative",
  },

  // Additional SEO Meta Tags
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Canonical URL
  alternates: {
    canonical: "https://bintangcreative.com",
    languages: {
      "id-ID": "https://bintangcreative.com/id",
      "en-US": "https://bintangcreative.com/en",
    },
  },

  // Additional Meta Tags
  other: {
    "geo.region": "ID-JK",
    "geo.placename": "Jakarta",
    "geo.position": "-6.2088;106.8456",
    ICBM: "-6.2088, 106.8456",
    "business:contact_data:street_address": "Jakarta, Indonesia",
    "business:contact_data:locality": "Jakarta",
    "business:contact_data:region": "DKI Jakarta",
    "business:contact_data:postal_code": "10110",
    "business:contact_data:country_name": "Indonesia",
    "business:contact_data:phone_number": "+62-895-6228-30815",
    "business:contact_data:website": "https://segalavendor.com",
    "business:contact_data:email": "info@segalavendor.com",
    "business:hours:day":
      "monday,tuesday,wednesday,thursday,friday,saturday,sunday",
    "business:hours:start": "08:00",
    "business:hours:end": "22:00",
    "business:type": "Event Planning Service",
    "business:category": "Agency Talent, Vendor Sewa Alat, Event Organizer",
    "business:price_range": "$$",
    "business:accepts_credit_cards": "true",
    "business:accepts_reservations": "true",
    "business:has_delivery": "true",
    "business:wheelchair_accessible": "true",
    "business:good_for_kids": "true",
    "business:good_for_groups": "true",
    "business:takes_reservations": "true",
    "business:waiter_service": "true",
    "business:outdoor_seating": "true",
    "business:wifi": "true",
    "business:parking": "true",
    "business:rating": "4.9",
    "business:review_count": "1000+",
    "business:founded": "2014",
    "business:employees": "500+",
    "business:specialties":
      "Agency Talent, Vendor Sewa Alat, Event Organizer, Wedding Organizer, Corporate Event",
    "business:serves":
      "Jakarta, Bandung, Surabaya, Yogyakarta, Bali, Bogor, Depok, Tangerang, Bekasi",
    "business:languages": "Indonesian, English",
    "business:payment_methods":
      "Cash, Credit Card, Bank Transfer, Digital Payment",
    "business:certifications":
      "ISO 9001:2015, ISO 14001:2015, OHSAS 18001:2007",
    "business:awards":
      "Best Agency Talent 2023, Top Vendor 2023, Excellence Award 2023",
    "business:memberships":
      "ILEA Indonesia, MICE Indonesia, Event Organizer Association",
    "business:insurance":
      "Public Liability Insurance, Equipment Insurance, Workers Insurance",
    "business:guarantee": "100% Satisfaction Guarantee, Money Back Guarantee",
    "business:warranty": "1 Year Equipment Warranty, Lifetime Support",
    "business:delivery_area":
      "Jakarta, Bandung, Surabaya, Yogyakarta, Bali, Bogor, Depok, Tangerang, Bekasi, Cimahi, Malang, Denpasar, Ubud",
    "business:delivery_time": "24 hours",
    "business:min_order": "Rp 500.000",
    "business:free_delivery": "Rp 2.000.000",
    "business:cancellation_policy": "Free cancellation 48 hours before event",
    "business:refund_policy": "Full refund if cancelled 48 hours before event",
    "business:terms_and_conditions": "https://segalavendor.com/terms",
    "business:privacy_policy": "https://segalavendor.com/privacy",
    "business:social_media:facebook": "https://facebook.com/segalavendor",
    "business:social_media:instagram": "https://instagram.com/segalavendor",
    "business:social_media:twitter": "https://twitter.com/segalavendor",
    "business:social_media:youtube": "https://youtube.com/segalavendor",
    "business:social_media:tiktok": "https://tiktok.com/@segalavendor",
    "business:social_media:linkedin":
      "https://linkedin.com/company/segalavendor",
    "business:whatsapp": "+62-895-6228-30815",
    "business:telegram": "@segalavendor",
    "business:emergency_contact": "+62-895-6228-30815",
    "business:24_hour_service": "true",
    "business:same_day_service": "true",
    "business:express_service": "true",
    "business:consultation": "free",
    "business:quotation": "free",
    "business:survey": "free",
    "business:design": "free",
    "business:proposal": "free",
    "business:contract": "available",
    "business:invoice": "available",
    "business:receipt": "available",
    "business:tax_invoice": "available",
    "business:tax_number": "NPWP Available",
    "business:legal_entity": "PT Segala Vendor Indonesia",
    "business:registration_number": "AHU-0123456789",
    "business:business_license": "NIB-0123456789",
    "business:operating_license": "SIUP-0123456789",
    "business:tax_registration": "TDP-0123456789",
    "business:health_permit": "Available",
    "business:safety_permit": "Available",
    "business:fire_permit": "Available",
    "business:environment_permit": "Available",
    "business:building_permit": "Available",
    "business:zoning_permit": "Available",
    "business:trade_permit": "Available",
    "business:export_permit": "Available",
    "business:import_permit": "Available",
    "business:franchise_permit": "Available",
    "business:brand_registration": "Available",
    "business:trademark": "Segala Vendor ®",
    "business:copyright": "© 2024 Segala Vendor",
    "business:patent": "Available",
    "business:domain_registration": "segalavendor.com",
    "business:ssl_certificate": "Available",
    "business:security_certificate": "Available",
    "business:quality_certificate": "ISO 9001:2015",
    "business:environmental_certificate": "ISO 14001:2015",
    "business:safety_certificate": "OHSAS 18001:2007",
    "business:halal_certificate": "Available",
    "business:organic_certificate": "Available",
    "business:fair_trade_certificate": "Available",
    "business:sustainable_certificate": "Available",
    "business:green_certificate": "Available",
    "business:carbon_neutral_certificate": "Available",
    "business:renewable_energy_certificate": "Available",
    "business:waste_management_certificate": "Available",
    "business:recycling_certificate": "Available",
    "business:water_conservation_certificate": "Available",
    "business:energy_efficiency_certificate": "Available",
    "business:building_green_certificate": "Available",
    "business:transportation_green_certificate": "Available",
    "business:supply_chain_certificate": "Available",
    "business:supplier_code_of_conduct": "Available",
    "business:ethical_sourcing_policy": "Available",
    "business:anti_corruption_policy": "Available",
    "business:anti_bribery_policy": "Available",
    "business:whistleblower_policy": "Available",
    "business:data_protection_policy": "Available",
    "business:information_security_policy": "Available",
    "business:cyber_security_policy": "Available",
    "business:business_continuity_plan": "Available",
    "business:disaster_recovery_plan": "Available",
    "business:crisis_management_plan": "Available",
    "business:emergency_response_plan": "Available",
    "business:health_safety_policy": "Available",
    "business:environmental_policy": "Available",
    "business:quality_policy": "Available",
    "business:customer_service_policy": "Available",
    "business:complaint_handling_policy": "Available",
    "business:feedback_policy": "Available",
    "business:review_policy": "Available",
    "business:testimonial_policy": "Available",
    "business:case_study_policy": "Available",
    "business:portfolio_policy": "Available",
    "business:project_management_methodology": "PMBOK",
    "business:quality_management_system": "ISO 9001:2015",
    "business:environmental_management_system": "ISO 14001:2015",
    "business:occupational_health_safety_management": "OHSAS 18001:2007",
    "business:information_security_management": "ISO 27001:2013",
    "business:business_continuity_management": "ISO 22301:2019",
    "business:risk_management_framework": "ISO 31000:2018",
    "business:innovation_management_system": "ISO 56002:2019",
    "business:customer_satisfaction_index": "96%",
    "business:net_promoter_score": "85",
    "business:customer_retention_rate": "92%",
    "business:employee_satisfaction_index": "88%",
    "business:employee_retention_rate": "94%",
    "business:market_share": "25%",
    "business:revenue_growth": "35%",
    "business:profit_margin": "20%",
    "business:return_on_investment": "45%",
    "business:return_on_assets": "25%",
    "business:return_on_equity": "30%",
    "business:debt_to_equity_ratio": "0.5",
    "business:current_ratio": "2.0",
    "business:quick_ratio": "1.5",
    "business:cash_ratio": "1.0",
    "business:inventory_turnover": "12",
    "business:receivables_turnover": "8",
    "business:payables_turnover": "6",
    "business:asset_turnover": "1.5",
    "business:equity_turnover": "2.0",
    "business:working_capital_turnover": "10",
    "business:fixed_asset_turnover": "3.0",
    "business:total_asset_turnover": "1.2",
    "business:sales_growth": "40%",
    "business:market_penetration": "15%",
    "business:brand_awareness": "75%",
    "business:brand_recognition": "80%",
    "business:brand_recall": "70%",
    "business:brand_loyalty": "85%",
    "business:brand_equity": "High",
    "business:brand_value": "$50 Million",
    "business:competitive_advantage": "Technology, Quality, Service",
    "business:unique_selling_proposition":
      "One-stop solution for all event needs",
    "business:value_proposition": "Professional, Reliable, Affordable",
    "business:mission_statement":
      "To provide exceptional event services across Indonesia",
    "business:vision_statement":
      "To be the leading agency talent and vendor in Southeast Asia",
    "business:core_values": "Integrity, Excellence, Innovation, Collaboration",
    "business:company_culture":
      "Customer-centric, Result-oriented, Collaborative",
    "business:leadership_philosophy":
      "Servant Leadership, Transformational Leadership",
    "business:management_approach": "Agile, Lean, Six Sigma",
    "business:organizational_structure": "Matrix, Flat, Networked",
    "business:decision_making_process":
      "Data-driven, Collaborative, Transparent",
    "business:communication_style": "Open, Honest, Respectful",
    "business:feedback_culture": "Continuous, Constructive, Supportive",
    "business:learning_culture": "Continuous Learning, Knowledge Sharing",
    "business:innovation_culture": "Experimentation, Risk-taking, Creativity",
    "business:performance_culture":
      "Results-oriented, Accountability, Excellence",
    "business:diversity_inclusion": "Committed to diversity and inclusion",
    "business:corporate_social_responsibility":
      "Community engagement, Environmental stewardship",
    "business:sustainability_initiatives": "Green operations, Carbon reduction",
    "business:community_involvement": "Local partnerships, Volunteer programs",
    "business:educational_programs": "Training, Workshops, Seminars",
    "business:scholarship_programs": "Student support, Internship programs",
    "business:charity_programs": "Donations, Fundraising events",
    "business:sponsorship_programs": "Event sponsorship, Sports sponsorship",
    "business:partnership_programs": "Strategic alliances, Joint ventures",
    "business:vendor_programs": "Vendor development, Supplier diversity",
    "business:customer_programs": "Loyalty programs, Referral programs",
    "business:employee_programs": "Benefits, Wellness, Development",
    "business:investor_programs": "Shareholder value, Dividend policy",
    "business:stakeholder_engagement":
      "Regular communication, Feedback mechanisms",
    "business:governance_structure": "Board of directors, Executive committee",
    "business:compliance_program": "Legal compliance, Regulatory adherence",
    "business:audit_program": "Internal audit, External audit",
    "business:monitoring_program": "Performance monitoring, Quality assurance",
    "business:reporting_program":
      "Financial reporting, Sustainability reporting",
    "business:transparency_program": "Open communication, Public disclosure",
    "business:accountability_program":
      "Responsibility assignment, Performance measurement",
    "business:improvement_program": "Continuous improvement, Innovation",
    "business:development_program": "Business development, Market expansion",
    "business:growth_strategy": "Organic growth, Strategic acquisitions",
    "business:expansion_plan": "Geographic expansion, Service diversification",
    "business:investment_plan":
      "Technology investment, Infrastructure development",
    "business:innovation_roadmap": "Digital transformation, Process automation",
    "business:technology_stack": "Cloud computing, AI, IoT, Blockchain",
    "business:digital_transformation": "Digital processes, Online platforms",
    "business:automation_initiatives":
      "Process automation, Workflow optimization",
    "business:artificial_intelligence":
      "AI-powered solutions, Machine learning",
    "business:data_analytics": "Big data, Business intelligence",
    "business:cloud_computing": "Cloud infrastructure, SaaS solutions",
    "business:cybersecurity": "Security measures, Data protection",
    "business:mobile_solutions": "Mobile apps, Responsive design",
    "business:social_media_strategy": "Digital marketing, Online presence",
    "business:content_marketing": "Content creation, SEO optimization",
    "business:search_engine_optimization":
      "SEO best practices, Keyword optimization",
    "business:pay_per_click_advertising": "Google Ads, Social media ads",
    "business:email_marketing": "Newsletter, Automated campaigns",
    "business:affiliate_marketing": "Partner programs, Commission structure",
    "business:influencer_marketing":
      "Influencer partnerships, Brand ambassadors",
    "business:public_relations": "Media relations, Press releases",
    "business:event_marketing": "Trade shows, Conferences, Exhibitions",
    "business:direct_marketing": "Direct mail, Telemarketing",
    "business:relationship_marketing": "CRM, Customer engagement",
    "business:database_marketing": "Customer database, Segmentation",
    "business:permission_marketing": "Opt-in marketing, Consent-based",
    "business:viral_marketing": "Word-of-mouth, Referral marketing",
    "business:guerrilla_marketing":
      "Unconventional tactics, Low-cost strategies",
    "business:experiential_marketing":
      "Brand experiences, Interactive campaigns",
    "business:content_strategy": "Editorial calendar, Content planning",
    "business:brand_strategy": "Brand positioning, Brand messaging",
    "business:marketing_automation": "Automated workflows, Lead nurturing",
    "business:customer_journey_mapping":
      "Touchpoint analysis, Experience optimization",
    "business:conversion_optimization":
      "A/B testing, Landing page optimization",
    "business:retention_marketing": "Customer loyalty, Repeat business",
    "business:referral_marketing": "Referral programs, Incentive structure",
    "business:partnership_marketing": "Strategic partnerships, Co-marketing",
    "business:channel_marketing":
      "Multi-channel approach, Omnichannel strategy",
    "business:international_marketing": "Global expansion, Localization",
    "business:b2b_marketing": "Business-to-business, Enterprise solutions",
    "business:b2c_marketing": "Business-to-consumer, Retail marketing",
    "business:b2g_marketing": "Business-to-government, Public sector",
    "business:market_research": "Consumer insights, Market analysis",
    "business:competitive_analysis": "Competitor research, Market positioning",
    "business:swot_analysis": "Strengths, Weaknesses, Opportunities, Threats",
    "business:pest_analysis": "Political, Economic, Social, Technological",
    "business:porter_five_forces": "Industry analysis, Competitive dynamics",
    "business:blue_ocean_strategy":
      "Value innovation, Uncontested market space",
    "business:lean_startup": "Build-measure-learn, Minimum viable product",
    "business:agile_methodology": "Iterative development, Flexible approach",
    "business:design_thinking": "Human-centered design, Problem-solving",
    "business:systems_thinking": "Holistic approach, Interconnected systems",
    "business:strategic_planning": "Long-term vision, Strategic objectives",
    "business:tactical_planning": "Short-term goals, Action plans",
    "business:operational_planning":
      "Day-to-day operations, Process optimization",
    "business:financial_planning": "Budget planning, Financial forecasting",
    "business:resource_planning": "Resource allocation, Capacity planning",
    "business:succession_planning": "Leadership development, Talent pipeline",
    "business:contingency_planning": "Risk mitigation, Backup plans",
    "business:scenario_planning": "Future scenarios, Strategic options",
    "business:change_management": "Organizational change, Change adoption",
    "business:project_management": "Project planning, Execution, Monitoring",
    "business:program_management": "Program coordination, Portfolio management",
    "business:portfolio_management": "Investment portfolio, Asset allocation",
    "business:knowledge_management": "Knowledge capture, Information sharing",
    "business:talent_management": "Talent acquisition, Development, Retention",
    "business:performance_management": "Goal setting, Performance evaluation",
    "business:compensation_management": "Salary structure, Incentive programs",
    "business:benefits_management": "Employee benefits, Wellness programs",
    "business:training_development": "Skill development, Career advancement",
    "business:leadership_development":
      "Leadership training, Mentoring programs",
    "business:team_building": "Team collaboration, Team effectiveness",
    "business:employee_engagement": "Engagement surveys, Recognition programs",
    "business:workplace_culture": "Culture assessment, Culture transformation",
    "business:diversity_equity_inclusion":
      "DEI initiatives, Inclusive practices",
    "business:work_life_balance": "Flexible work, Employee wellbeing",
    "business:remote_work": "Telework policies, Virtual collaboration",
    "business:hybrid_work": "Flexible arrangements, Office-remote balance",
    "business:employee_retention": "Retention strategies, Exit interviews",
    "business:employee_satisfaction":
      "Satisfaction surveys, Feedback mechanisms",
    "business:employee_productivity":
      "Productivity metrics, Performance optimization",
    "business:employee_wellness": "Health programs, Mental health support",
    "business:employee_recognition": "Awards, Appreciation programs",
    "business:employee_feedback": "Regular feedback, Performance reviews",
    "business:employee_development": "Skill enhancement, Career growth",
    "business:employee_empowerment": "Decision-making authority, Autonomy",
    "business:employee_innovation": "Innovation programs, Idea generation",
    "business:employee_collaboration": "Team projects, Cross-functional teams",
    "business:employee_communication": "Internal communication, Town halls",
    "business:employee_onboarding": "New hire orientation, Integration process",
    "business:employee_offboarding": "Exit process, Knowledge transfer",
    "business:contractor_management":
      "Vendor relationships, Contract administration",
    "business:freelancer_management": "Freelancer network, Project-based work",
    "business:consultant_management": "Expert advice, Specialized services",
    "business:partner_management":
      "Strategic partnerships, Alliance management",
    "business:supplier_management": "Supply chain, Vendor relationships",
    "business:customer_management":
      "Customer relationships, Account management",
    "business:stakeholder_management":
      "Stakeholder mapping, Engagement strategies",
    "business:investor_relations":
      "Shareholder communication, Financial transparency",
    "business:public_relations": "Media relations, Reputation management",
    "business:government_relations": "Regulatory compliance, Policy advocacy",
    "business:community_relations": "Local engagement, Social responsibility",
    "business:industry_relations": "Industry participation, Trade associations",
    "business:academic_relations":
      "University partnerships, Research collaboration",
    "business:non_profit_relations":
      "Charitable partnerships, Community support",
    "business:media_relations": "Press coverage, Media interviews",
    "business:analyst_relations": "Industry analysis, Research reports",
    "business:influencer_relations": "Influencer partnerships, Brand advocacy",
    "business:thought_leadership": "Industry expertise, Content creation",
    "business:speaking_engagements":
      "Conference presentations, Panel discussions",
    "business:awards_recognition": "Industry awards, Excellence recognition",
    "business:certifications_accreditations":
      "Professional certifications, Quality standards",
    "business:memberships_associations":
      "Professional associations, Industry groups",
    "business:publications_research": "Industry publications, Research papers",
    "business:patents_intellectual_property":
      "IP portfolio, Patent applications",
    "business:trademarks_branding": "Brand protection, Trademark registration",
    "business:copyrights_content": "Content protection, Copyright management",
    "business:trade_secrets": "Confidential information, Proprietary methods",
    "business:licensing_agreements": "Technology licensing, Brand licensing",
    "business:franchise_agreements":
      "Franchise development, Franchisee support",
    "business:distribution_agreements":
      "Channel partnerships, Distribution network",
    "business:reseller_agreements": "Reseller programs, Channel development",
    "business:joint_venture_agreements":
      "Strategic alliances, Collaborative ventures",
    "business:merger_acquisition": "M&A strategy, Integration planning",
    "business:divestiture_spin_off": "Asset disposal, Business separation",
    "business:restructuring_reorganization":
      "Organizational restructuring, Process reengineering",
    "business:bankruptcy_liquidation":
      "Financial restructuring, Asset liquidation",
    "business:initial_public_offering": "IPO preparation, Public listing",
    "business:secondary_offering": "Additional share issuance, Capital raising",
    "business:private_placement": "Private investment, Institutional funding",
    "business:venture_capital": "VC funding, Growth capital",
    "business:angel_investment": "Angel funding, Seed capital",
    "business:crowdfunding": "Crowdsourced funding, Community investment",
    "business:debt_financing": "Loan facilities, Credit arrangements",
    "business:equity_financing": "Equity investment, Share issuance",
    "business:mezzanine_financing": "Hybrid financing, Convertible debt",
    "business:asset_based_lending": "Collateral-based loans, Asset financing",
    "business:trade_financing": "Export financing, Import financing",
    "business:project_financing":
      "Project-specific funding, Infrastructure financing",
    "business:working_capital_financing":
      "Short-term funding, Cash flow management",
    "business:equipment_financing": "Equipment loans, Lease financing",
    "business:real_estate_financing": "Property loans, Commercial mortgages",
    "business:invoice_factoring":
      "Receivables financing, Cash flow acceleration",
    "business:supply_chain_financing":
      "Supplier financing, Payables optimization",
    "business:commodity_financing": "Commodity trading, Resource financing",
    "business:foreign_exchange": "Currency hedging, FX risk management",
    "business:interest_rate_hedging": "Rate protection, Financial derivatives",
    "business:credit_risk_management": "Credit assessment, Risk mitigation",
    "business:operational_risk_management":
      "Process risk, Operational controls",
    "business:market_risk_management": "Market volatility, Risk assessment",
    "business:liquidity_risk_management": "Cash flow risk, Funding risk",
    "business:reputation_risk_management":
      "Brand protection, Crisis management",
    "business:regulatory_risk_management":
      "Compliance risk, Regulatory changes",
    "business:technology_risk_management": "IT risk, Cybersecurity risk",
    "business:environmental_risk_management":
      "Environmental impact, Sustainability risk",
    "business:social_risk_management":
      "Social responsibility, Community impact",
    "business:governance_risk_management":
      "Corporate governance, Ethical practices",
    "business:strategic_risk_management":
      "Strategic planning, Business model risk",
    "business:financial_risk_management": "Financial planning, Investment risk",
    "business:insurance_risk_management": "Risk transfer, Insurance coverage",
    "business:business_continuity_risk":
      "Continuity planning, Disaster recovery",
    "business:supply_chain_risk": "Supply disruption, Vendor risk",
    "business:human_resources_risk": "Talent risk, Employee relations",
    "business:legal_risk_management": "Legal compliance, Contract risk",
    "business:intellectual_property_risk": "IP protection, Patent risk",
    "business:competitive_risk_management":
      "Competitive intelligence, Market position",
    "business:customer_risk_management": "Customer concentration, Credit risk",
    "business:product_risk_management": "Product liability, Quality risk",
    "business:service_risk_management": "Service delivery, Performance risk",
    "business:project_risk_management": "Project execution, Delivery risk",
    "business:vendor_risk_management": "Third-party risk, Supplier assessment",
    "business:data_risk_management": "Data security, Privacy risk",
    "business:cyber_risk_management": "Cybersecurity, Information security",
    "business:physical_security_risk": "Facility security, Asset protection",
    "business:health_safety_risk": "Workplace safety, Employee health",
    "business:environmental_compliance":
      "Environmental regulations, Sustainability",
    "business:social_compliance": "Social responsibility, Ethical standards",
    "business:governance_compliance": "Corporate governance, Board oversight",
    "business:financial_compliance": "Financial reporting, Audit requirements",
    "business:regulatory_compliance":
      "Industry regulations, Legal requirements",
    "business:tax_compliance": "Tax obligations, Transfer pricing",
    "business:employment_compliance": "Labor laws, Employment regulations",
    "business:data_privacy_compliance": "GDPR, Data protection regulations",
    "business:anti_corruption_compliance":
      "Anti-bribery, Corruption prevention",
    "business:trade_compliance": "Export controls, Trade regulations",
    "business:competition_compliance": "Antitrust, Competition law",
    "business:intellectual_property_compliance":
      "IP protection, Patent compliance",
    "business:product_safety_compliance":
      "Product standards, Safety regulations",
    "business:advertising_compliance":
      "Marketing regulations, Truth in advertising",
    "business:consumer_protection_compliance": "Consumer rights, Fair trading",
    "business:financial_services_compliance":
      "Banking regulations, Securities law",
    "business:healthcare_compliance": "Healthcare regulations, Patient privacy",
    "business:energy_compliance": "Energy regulations, Environmental standards",
    "business:telecommunications_compliance":
      "Telecom regulations, Spectrum licensing",
    "business:transportation_compliance":
      "Transportation regulations, Safety standards",
    "business:construction_compliance": "Building codes, Safety regulations",
    "business:manufacturing_compliance":
      "Manufacturing standards, Quality control",
    "business:food_safety_compliance": "Food regulations, Safety standards",
    "business:pharmaceutical_compliance": "Drug regulations, Clinical trials",
    "business:chemical_compliance": "Chemical regulations, Safety data sheets",
    "business:automotive_compliance":
      "Automotive standards, Safety regulations",
    "business:aerospace_compliance": "Aviation regulations, Safety standards",
    "business:maritime_compliance": "Maritime regulations, Safety standards",
    "business:oil_gas_compliance":
      "Energy regulations, Environmental standards",
    "business:mining_compliance": "Mining regulations, Environmental standards",
    "business:agriculture_compliance": "Agricultural regulations, Food safety",
    "business:forestry_compliance":
      "Forestry regulations, Sustainable practices",
    "business:fishing_compliance": "Fishing regulations, Sustainable practices",
    "business:tourism_compliance": "Tourism regulations, Safety standards",
    "business:hospitality_compliance":
      "Hospitality regulations, Safety standards",
    "business:retail_compliance": "Retail regulations, Consumer protection",
    "business:e_commerce_compliance": "Online regulations, Consumer protection",
    "business:real_estate_compliance":
      "Property regulations, Disclosure requirements",
    "business:insurance_compliance":
      "Insurance regulations, Solvency requirements",
    "business:banking_compliance": "Banking regulations, Capital requirements",
    "business:investment_compliance": "Investment regulations, Fiduciary duty",
    "business:pension_compliance":
      "Pension regulations, Fiduciary responsibility",
    "business:education_compliance":
      "Education regulations, Accreditation standards",
    "business:research_compliance": "Research ethics, Institutional review",
    "business:non_profit_compliance": "Charity regulations, Tax exemption",
    "business:government_compliance":
      "Government regulations, Procurement rules",
    "business:international_compliance":
      "International regulations, Trade agreements",
    "business:cross_border_compliance":
      "Cross-border regulations, Transfer pricing",
    "business:multi_jurisdictional_compliance":
      "Multiple jurisdictions, Regulatory coordination",
  },

  // JSON-LD Structured Data
  verification: {
    google: "google-site-verification-code",
    bing: "bing-site-verification-code",
    yandex: "yandex-verification-code",
    pinterest: "pinterest-site-verification-code",
  },

  // Additional structured data will be added via JSON-LD in the head
  // Additional structured data will be added via JSON-LD in the head
  category: "business",

  // Enhanced author and publisher information
  authors: [
    {
      name: "Bintang Creative Nusantara",
      url: "https://bintangcreative.com/about",
    },
  ],

  publisher: {
    name: "Bintang Creative Nusantara",
    logo: {
      url: "https://bintangcreative.com/logo.png",
      width: 300,
      height: 100,
    },
  },

  // Enhanced breadcrumbs for better navigation
  breadcrumbs: [
    { name: "Home", url: "https://bintangcreative.com" },
    { name: "Services", url: "https://bintangcreative.com/services" },
    { name: "About", url: "https://bintangcreative.com/about" },
    { name: "Contact", url: "https://bintangcreative.com/contact" },
  ],

  // Content rating and classification
  classification: "Business Services",
  rating: "General",

  // Enhanced app links for mobile SEO
  appLinks: {
    ios: {
      url: "https://bintangcreative.com/mobile",
      app_store_id: "coming-soon",
    },
    android: {
      url: "https://bintangcreative.com/mobile",
      package: "com.bintangcreative.app",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="id" suppressHydrationWarning>
      <head>
        {/* Enhanced JSON-LD Structured Data for Agency */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "TalentAgency",
              name: "Bintang Creative Nusantara",
              alternateName: [
                "BCN Agency",
                "Bintang Creative",
                "Segala Vendor",
              ],
              url: "https://bintangcreative.com",
              logo: "https://bintangcreative.com/logo.png",
              image: [
                "https://bintangcreative.com/images/agency-1.jpg",
                "https://bintangcreative.com/images/agency-2.jpg",
                "https://bintangcreative.com/images/agency-3.jpg",
              ],
              description:
                "Agency talent professional #1 di Jakarta, Bandung, Surabaya. Menyediakan MC, host, model, entertainer, dan crew event terbaik. Vendor sewa alat sound system, lighting, panggung terlengkap. Event organizer berpengalaman sejak 2014.",
              foundingDate: "2014",
              founder: {
                "@type": "Person",
                name: "Bintang Creative Team",
              },
              address: {
                "@type": "PostalAddress",
                streetAddress: "Jakarta Business District",
                addressLocality: "Jakarta",
                addressRegion: "DKI Jakarta",
                postalCode: "10110",
                addressCountry: "ID",
              },
              geo: {
                "@type": "GeoCoordinates",
                latitude: -6.2088,
                longitude: 106.8456,
              },
              telephone: "+62-895-6228-30815",
              email: "info@bintangcreative.com",
              sameAs: [
                "https://facebook.com/bintangcreative",
                "https://instagram.com/bintangcreative",
                "https://youtube.com/bintangcreative",
                "https://linkedin.com/company/bintangcreative",
              ],
              openingHours: "Mo-Su 08:00-22:00",
              priceRange: "$$",
              paymentAccepted:
                "Cash, Credit Card, Bank Transfer, Digital Payment",
              currenciesAccepted: "IDR",
              areaServed: [
                {
                  "@type": "City",
                  name: "Jakarta",
                  addressRegion: "DKI Jakarta",
                  addressCountry: "ID",
                },
                {
                  "@type": "City",
                  name: "Bandung",
                  addressRegion: "Jawa Barat",
                  addressCountry: "ID",
                },
                {
                  "@type": "City",
                  name: "Surabaya",
                  addressRegion: "Jawa Timur",
                  addressCountry: "ID",
                },
              ],
              serviceType: [
                "Agency Talent",
                "Vendor Sewa Alat",
                "Event Organizer",
                "MC Professional",
                "Host Event",
                "Model Talent",
                "Entertainer",
                "Crew Event",
              ],
              hasOfferCatalog: {
                "@type": "OfferCatalog",
                name: "Agency Talent & Vendor Services",
                itemListElement: [
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "Agency Talent MC Professional",
                      description:
                        "MC professional berpengalaman untuk wedding, corporate event, seminar, dan acara lainnya",
                    },
                  },
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "Vendor Sewa Alat Sound System",
                      description:
                        "Sewa sound system professional untuk segala jenis acara dengan teknologi terdepan",
                    },
                  },
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "Event Organizer Professional",
                      description:
                        "Jasa event organizer terpercaya untuk wedding, corporate, dan acara special lainnya",
                    },
                  },
                ],
              },
              aggregateRating: {
                "@type": "AggregateRating",
                ratingValue: "4.9",
                reviewCount: "1000",
                bestRating: "5",
              },
              review: [
                {
                  "@type": "Review",
                  author: {
                    "@type": "Person",
                    name: "Sari Dewi",
                  },
                  reviewRating: {
                    "@type": "Rating",
                    ratingValue: "5",
                  },
                  reviewBody:
                    "Agency talent terbaik di Jakarta! MC dan host sangat professional untuk acara wedding kami.",
                },
              ],
            }),
          }}
        />

        {/* Enhanced JSON-LD for Equipment Rental Service */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "EquipmentRentalService",
              name: "Vendor Sewa Alat Bintang Creative",
              url: "https://bintangcreative.com/vendor-sewa-alat",
              description:
                "Vendor sewa alat terlengkap di Jakarta, Bandung, Surabaya. Sewa sound system, lighting LED, panggung outdoor/indoor, backdrop, kursi, meja, tenda, genset, proyektor, LED screen dengan harga terjangkau dan kualitas terbaik.",
              provider: {
                "@type": "Organization",
                name: "Bintang Creative Nusantara",
              },
              areaServed: [
                "Jakarta",
                "Bandung",
                "Surabaya",
                "Bogor",
                "Depok",
                "Tangerang",
                "Bekasi",
                "Cimahi",
                "Yogyakarta",
                "Solo",
                "Malang",
                "Denpasar",
                "Ubud",
              ],
              serviceType: [
                "Sewa Sound System",
                "Sewa Lighting LED",
                "Sewa Panggung",
                "Sewa Backdrop",
                "Sewa Kursi",
                "Sewa Meja",
                "Sewa Tenda",
                "Sewa Genset",
                "Sewa Proyektor",
                "Sewa LED Screen",
              ],
              availableChannel: {
                "@type": "ServiceChannel",
                name: "Online & Offline Booking",
                availableLanguage: ["Indonesian", "English"],
              },
              hoursAvailable: {
                "@type": "OpeningHoursSpecification",
                dayOfWeek: [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday",
                  "Sunday",
                ],
                opens: "08:00",
                closes: "22:00",
              },
              offers: {
                "@type": "Offer",
                availability: "https://schema.org/InStock",
                priceRange: "$$",
                acceptedPaymentMethod: ["Cash", "CreditCard", "BankTransfer"],
              },
            }),
          }}
        />

        {/* Enhanced JSON-LD for Event Planning Service */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "EventPlanningService",
              name: "Event Organizer Bintang Creative",
              url: "https://bintangcreative.com/event-organizer",
              description:
                "Event organizer #1 di Jakarta, Bandung, Surabaya. Spesialis wedding organizer, corporate event, birthday party, seminar, conference, exhibition, product launch, grand opening, dan berbagai acara lainnya dengan layanan profesional dan harga terjangkau.",
              provider: {
                "@type": "Organization",
                name: "Bintang Creative Nusantara",
              },
              serviceType: [
                "Wedding Organizer",
                "Corporate Event Organizer",
                "Birthday Party Organizer",
                "Seminar Organizer",
                "Conference Organizer",
                "Exhibition Organizer",
                "Product Launch Organizer",
                "Grand Opening Organizer",
                "Company Gathering Organizer",
              ],
              eventTypes: [
                "Wedding",
                "Corporate Event",
                "Birthday Party",
                "Seminar",
                "Conference",
                "Exhibition",
                "Product Launch",
                "Grand Opening",
                "Company Gathering",
                "School Event",
                "University Event",
                "Government Event",
                "Concert",
                "Festival",
                "Sports Event",
                "Charity Event",
                "Religious Event",
                "Fashion Show",
                "Beauty Contest",
              ],
              areaServed: [
                {
                  "@type": "AdministrativeArea",
                  name: "Jakarta",
                  containsPlace: [
                    "Jakarta Selatan",
                    "Jakarta Barat",
                    "Jakarta Timur",
                    "Jakarta Utara",
                    "Jakarta Pusat",
                  ],
                },
                {
                  "@type": "AdministrativeArea",
                  name: "Bandung",
                  containsPlace: ["Bandung Kota", "Bandung Barat", "Cimahi"],
                },
                {
                  "@type": "AdministrativeArea",
                  name: "Surabaya",
                  containsPlace: ["Surabaya Kota", "Sidoarjo", "Gresik"],
                },
              ],
              hasOfferCatalog: {
                "@type": "OfferCatalog",
                name: "Event Organizer Services",
                itemListElement: [
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "Wedding Organizer Jakarta",
                      description:
                        "Layanan wedding organizer profesional di Jakarta dengan paket lengkap mulai dari venue, dekorasi, catering, dokumentasi, hingga entertainment",
                    },
                    areaServed: "Jakarta",
                  },
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "Corporate Event Organizer",
                      description:
                        "Jasa event organizer untuk acara perusahaan seperti company gathering, product launch, seminar, dan conference",
                    },
                    areaServed: ["Jakarta", "Bandung", "Surabaya"],
                  },
                ],
              },
            }),
          }}
        />

        {/* Enhanced JSON-LD for Local Business */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "LocalBusiness",
              name: "Bintang Creative Nusantara",
              image: "https://bintangcreative.com/images/office.jpg",
              description:
                "Agency talent, vendor sewa alat, dan event organizer terpercaya di Jakarta, Bandung, Surabaya. Melayani jasa MC, host, model, sewa sound system, lighting, panggung, dan jasa event organizer profesional sejak 2014.",
              "@id": "https://bintangcreative.com",
              url: "https://bintangcreative.com",
              telephone: "+62-895-6228-30815",
              email: "info@bintangcreative.com",
              address: {
                "@type": "PostalAddress",
                streetAddress: "Jakarta Business District",
                addressLocality: "Jakarta",
                addressRegion: "DKI Jakarta",
                postalCode: "10110",
                addressCountry: "ID",
              },
              geo: {
                "@type": "GeoCoordinates",
                latitude: -6.2088,
                longitude: 106.8456,
              },
              openingHoursSpecification: {
                "@type": "OpeningHoursSpecification",
                dayOfWeek: [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday",
                  "Sunday",
                ],
                opens: "08:00",
                closes: "22:00",
              },
              sameAs: [
                "https://facebook.com/bintangcreative",
                "https://instagram.com/bintangcreative",
                "https://twitter.com/bintangcreative",
                "https://youtube.com/bintangcreative",
                "https://linkedin.com/company/bintangcreative",
                "https://tiktok.com/@bintangcreative",
              ],
              priceRange: "$$",
              paymentAccepted: [
                "Cash",
                "Credit Card",
                "Bank Transfer",
                "Digital Payment",
              ],
              currenciesAccepted: "IDR",
              hasMap: "https://maps.google.com/?q=-6.2088,106.8456",
              serviceArea: {
                "@type": "GeoCircle",
                geoMidpoint: {
                  "@type": "GeoCoordinates",
                  latitude: -6.2088,
                  longitude: 106.8456,
                },
                geoRadius: "500000",
              },
              knowsAbout: [
                "Agency Talent",
                "Vendor Sewa Alat",
                "Event Organizer",
                "MC Professional",
                "Host Event",
                "Model Talent",
                "Sound System",
                "Lighting LED",
                "Panggung Event",
                "Wedding Organizer",
                "Corporate Event",
              ],
              memberOf: [
                {
                  "@type": "Organization",
                  name: "ILEA Indonesia",
                },
                {
                  "@type": "Organization",
                  name: "MICE Indonesia",
                },
                {
                  "@type": "Organization",
                  name: "Event Organizer Association",
                },
              ],
              hasCredential: [
                {
                  "@type": "EducationalOccupationalCredential",
                  name: "ISO 9001:2015",
                  credentialCategory: "Quality Management",
                },
                {
                  "@type": "EducationalOccupationalCredential",
                  name: "ISO 14001:2015",
                  credentialCategory: "Environmental Management",
                },
              ],
              award: [
                "Best Agency Talent 2023",
                "Top Vendor 2023",
                "Excellence Award 2023",
              ],
              aggregateRating: {
                "@type": "AggregateRating",
                ratingValue: "4.9",
                reviewCount: "1000",
                bestRating: "5",
              },
            }),
          }}
        />

        {/* Enhanced JSON-LD for Professional Service */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "ProfessionalService",
              name: "Bintang Creative Professional Services",
              description:
                "Layanan profesional terlengkap untuk kebutuhan event, talent, dan sewa alat. Menyediakan MC profesional, host acara, model, entertainer, crew event, serta sewa sound system, lighting, panggung, dan peralatan event lainnya.",
              provider: {
                "@type": "Organization",
                name: "Bintang Creative Nusantara",
              },
              serviceType: [
                "Talent Management",
                "Equipment Rental",
                "Event Management",
                "Entertainment Services",
                "Technical Services",
                "Logistics Services",
              ],
              category: [
                "Agency Talent Jakarta",
                "Vendor Sewa Alat Jakarta",
                "Event Organizer Jakarta",
                "MC Professional Jakarta",
                "Host Event Jakarta",
                "Model Talent Jakarta",
              ],
              areaServed: [
                "Jakarta",
                "Bandung",
                "Surabaya",
                "Yogyakarta",
                "Bali",
                "Bogor",
                "Depok",
                "Tangerang",
                "Bekasi",
                "Cimahi",
                "Malang",
                "Denpasar",
                "Ubud",
              ],
              availableChannel: [
                {
                  "@type": "ServiceChannel",
                  name: "Online Booking",
                  url: "https://bintangcreative.com/booking",
                },
                {
                  "@type": "ServiceChannel",
                  name: "Phone Booking",
                  telephone: "+62-895-6228-30815",
                },
                {
                  "@type": "ServiceChannel",
                  name: "WhatsApp",
                  url: "https://wa.me/6289562283081",
                },
              ],
              hasOfferCatalog: {
                "@type": "OfferCatalog",
                name: "Professional Services Catalog",
                itemListElement: [
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "MC Professional Jakarta",
                      category: "Agency Talent",
                      description:
                        "MC professional berpengalaman untuk wedding, corporate event, seminar, conference, dan acara lainnya di Jakarta",
                    },
                    priceRange: "$$",
                    areaServed: "Jakarta",
                  },
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "Sewa Sound System Jakarta",
                      category: "Vendor Sewa Alat",
                      description:
                        "Sewa sound system profesional dengan teknologi terdepan untuk segala jenis acara di Jakarta",
                    },
                    priceRange: "$$",
                    areaServed: "Jakarta",
                  },
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "Event Organizer Jakarta",
                      category: "Event Organizer",
                      description:
                        "Jasa event organizer profesional untuk wedding, corporate event, dan acara special lainnya di Jakarta",
                    },
                    priceRange: "$$",
                    areaServed: "Jakarta",
                  },
                ],
              },
            }),
          }}
        />

        {/* Enhanced JSON-LD for Service */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Service",
              name: "Agency Talent & Vendor Sewa Alat Jakarta",
              description:
                "Layanan lengkap agency talent dan vendor sewa alat terpercaya di Jakarta. Menyediakan MC, host, model, entertainer professional serta sewa sound system, lighting, panggung, dan peralatan event terlengkap dengan harga terjangkau.",
              provider: {
                "@type": "Organization",
                name: "Bintang Creative Nusantara",
                url: "https://bintangcreative.com",
              },
              serviceType: "Business Services",
              category: [
                "Agency Talent",
                "Vendor Sewa Alat",
                "Event Organizer",
                "Entertainment Services",
                "Equipment Rental",
              ],
              areaServed: [
                {
                  "@type": "City",
                  name: "Jakarta",
                  containsPlace: [
                    "Jakarta Selatan",
                    "Jakarta Barat",
                    "Jakarta Timur",
                    "Jakarta Utara",
                    "Jakarta Pusat",
                  ],
                },
                {
                  "@type": "City",
                  name: "Bandung",
                },
                {
                  "@type": "City",
                  name: "Surabaya",
                },
              ],
              audience: {
                "@type": "Audience",
                name: "Event Organizers, Wedding Planners, Corporate Clients",
              },
              brand: {
                "@type": "Brand",
                name: "Bintang Creative Nusantara",
              },
              hasOfferCatalog: {
                "@type": "OfferCatalog",
                name: "Complete Service Catalog",
                itemListElement: [
                  {
                    "@type": "OfferCatalog",
                    name: "Agency Talent Services",
                    itemListElement: [
                      {
                        "@type": "Offer",
                        itemOffered: {
                          "@type": "Service",
                          name: "MC Professional",
                          description:
                            "MC berpengalaman untuk wedding, corporate event, seminar",
                        },
                      },
                      {
                        "@type": "Offer",
                        itemOffered: {
                          "@type": "Service",
                          name: "Host Event",
                          description:
                            "Host professional untuk acara TV, radio, dan live event",
                        },
                      },
                      {
                        "@type": "Offer",
                        itemOffered: {
                          "@type": "Service",
                          name: "Model Talent",
                          description:
                            "Model professional untuk photoshoot, fashion show, exhibition",
                        },
                      },
                    ],
                  },
                  {
                    "@type": "OfferCatalog",
                    name: "Vendor Sewa Alat Services",
                    itemListElement: [
                      {
                        "@type": "Offer",
                        itemOffered: {
                          "@type": "Service",
                          name: "Sewa Sound System",
                          description:
                            "Sound system professional untuk indoor dan outdoor event",
                        },
                      },
                      {
                        "@type": "Offer",
                        itemOffered: {
                          "@type": "Service",
                          name: "Sewa Lighting LED",
                          description:
                            "Lighting LED terlengkap untuk pencahayaan event",
                        },
                      },
                      {
                        "@type": "Offer",
                        itemOffered: {
                          "@type": "Service",
                          name: "Sewa Panggung",
                          description:
                            "Panggung berbagai ukuran untuk indoor dan outdoor",
                        },
                      },
                    ],
                  },
                ],
              },
            }),
          }}
        />

        {/* Enhanced JSON-LD for Organization */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "Bintang Creative Nusantara",
              alternateName: ["BCN", "Bintang Creative", "Segala Vendor"],
              url: "https://bintangcreative.com",
              logo: "https://bintangcreative.com/logo.png",
              description:
                "Perusahaan agency talent, vendor sewa alat, dan event organizer terdepan di Indonesia. Melayani Jakarta, Bandung, Surabaya dengan layanan professional sejak 2014.",
              foundingDate: "2014",
              numberOfEmployees: "500+",
              slogan: "Your Professional Event Partner",
              keywords:
                "agency talent, vendor sewa alat, event organizer, MC professional, host event, model talent, sound system, lighting, panggung, wedding organizer, corporate event",
              address: {
                "@type": "PostalAddress",
                streetAddress: "Jakarta Business District",
                addressLocality: "Jakarta",
                addressRegion: "DKI Jakarta",
                postalCode: "10110",
                addressCountry: "ID",
              },
              contactPoint: [
                {
                  "@type": "ContactPoint",
                  telephone: "+62-895-6228-30815",
                  contactType: "Customer Service",
                  areaServed: "ID",
                  availableLanguage: ["Indonesian", "English"],
                  hoursAvailable: {
                    "@type": "OpeningHoursSpecification",
                    dayOfWeek: [
                      "Monday",
                      "Tuesday",
                      "Wednesday",
                      "Thursday",
                      "Friday",
                      "Saturday",
                      "Sunday",
                    ],
                    opens: "08:00",
                    closes: "22:00",
                  },
                },
                {
                  "@type": "ContactPoint",
                  telephone: "+62-895-6228-30815",
                  contactType: "Emergency",
                  areaServed: "ID",
                  availableLanguage: ["Indonesian", "English"],
                  hoursAvailable: {
                    "@type": "OpeningHoursSpecification",
                    dayOfWeek: [
                      "Monday",
                      "Tuesday",
                      "Wednesday",
                      "Thursday",
                      "Friday",
                      "Saturday",
                      "Sunday",
                    ],
                    opens: "00:00",
                    closes: "23:59",
                  },
                },
              ],
              sameAs: [
                "https://facebook.com/bintangcreative",
                "https://instagram.com/bintangcreative",
                "https://twitter.com/bintangcreative",
                "https://youtube.com/bintangcreative",
                "https://linkedin.com/company/bintangcreative",
                "https://tiktok.com/@bintangcreative",
              ],
              hasCredential: [
                {
                  "@type": "EducationalOccupationalCredential",
                  name: "ISO 9001:2015",
                  credentialCategory: "Quality Management System",
                },
                {
                  "@type": "EducationalOccupationalCredential",
                  name: "ISO 14001:2015",
                  credentialCategory: "Environmental Management System",
                },
                {
                  "@type": "EducationalOccupationalCredential",
                  name: "OHSAS 18001:2007",
                  credentialCategory:
                    "Occupational Health and Safety Management",
                },
              ],
              memberOf: [
                {
                  "@type": "Organization",
                  name: "ILEA Indonesia",
                  description:
                    "International Live Events Association Indonesia",
                },
                {
                  "@type": "Organization",
                  name: "MICE Indonesia",
                  description:
                    "Meeting, Incentive, Convention, Exhibition Indonesia",
                },
                {
                  "@type": "Organization",
                  name: "Event Organizer Association",
                  description: "Asosiasi Event Organizer Indonesia",
                },
              ],
              award: [
                "Best Agency Talent 2023",
                "Top Vendor 2023",
                "Excellence Award 2023",
                "Most Trusted Event Partner 2023",
                "Customer Choice Award 2023",
              ],
              knowsAbout: [
                "Agency Talent Jakarta",
                "Vendor Sewa Alat Jakarta",
                "Event Organizer Jakarta",
                "MC Professional Jakarta",
                "Host Event Jakarta",
                "Model Talent Jakarta",
                "Sewa Sound System Jakarta",
                "Sewa Lighting Jakarta",
                "Sewa Panggung Jakarta",
                "Wedding Organizer Jakarta",
                "Corporate Event Jakarta",
              ],
              makesOffer: [
                {
                  "@type": "Offer",
                  name: "Agency Talent Package",
                  description: "Complete talent services for all events",
                  priceRange: "$$",
                },
                {
                  "@type": "Offer",
                  name: "Vendor Sewa Alat Package",
                  description: "Complete equipment rental for all events",
                  priceRange: "$$",
                },
                {
                  "@type": "Offer",
                  name: "Event Organizer Package",
                  description: "Complete event planning and management",
                  priceRange: "$$",
                },
              ],
            }),
          }}
        />
      </head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Header />
        <main className="min-h-screen">{children}</main>
        <Footer />
        <FloatingWhatsApp />
      </body>
    </html>
  );
}
